[soc]
soc1 ansible_host=127.0.0.1 ansible_port=50022 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/azure/id_ed25519 ansible_python_interpreter=/usr/bin/python3

[ad]
ad1 ansible_host=127.0.0.1 ansible_user=CORP\\azureuser ansible_password=YkyjsCuT1N1V ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_scheme=http ansible_winrm_server_cert_validation=ignore ansible_port=55985

[client]
client1 ansible_host=127.0.0.1 ansible_user=azureuser ansible_password=YkyjsCuT1N1V ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_scheme=http ansible_winrm_server_cert_validation=ignore ansible_port=55986

[windows:children]
ad
client

[windows:vars]
ansible_winrm_operation_timeout_sec=120
ansible_winrm_read_timeout_sec=180
ansible_winrm_connection_timeout=60



